/**
 * AUTO-GENERATED from app_control_requirements_54.json — do not edit by hand.
 * Regenerate with: node scripts/generate-controls.mjs
 */

export interface ControlRequirement {
  readonly domainId: string;
  readonly domain: string;
  readonly phase: string;
  readonly owner: string;
  readonly module: string;
  readonly severity: 1 | 2 | 3 | 4 | 5;
  readonly likelihoodBand: number;
  readonly prevention: string;
  readonly detection: string;
  readonly mitigation: string;
  readonly evidence: string;
  readonly hardRule: string;
  readonly fallback: string;
  readonly acceptanceTests: readonly string[];
}

export const CONTROLS: Readonly<Record<string, ControlRequirement>> = Object.freeze({
  D01: {
    domainId: "D01",
    domain: "Supplier identity and KYB",
    phase: "Onboarding",
    owner: "Procurement lead",
    module: "Supplier Registry",
    severity: 5,
    likelihoodBand: 3,
    prevention: "Require verified phone, national or commercial identity data, business location, and named representative before activation",
    detection: "Detect duplicate phones, IDs, bank accounts, addresses, devices, and conflicting names",
    mitigation: "Freeze new commitments and route the profile to manual review",
    evidence: "identity record, registration proof, verified contact, timestamped review",
    hardRule: "BLOCK activation when identity or representative authority is unverified",
    fallback: "Use a pre-approved alternate supplier only after its own verification",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D02: {
    domainId: "D02",
    domain: "Supplier authority and ownership",
    phase: "Onboarding",
    owner: "Procurement lead",
    module: "Supplier Registry",
    severity: 5,
    likelihoodBand: 2,
    prevention: "Capture owner, authorized seller, source relationship, and authority evidence",
    detection: "Compare seller name, source record, payment beneficiary, and prior ownership claims",
    mitigation: "Place the lot on ownership hold and prohibit settlement",
    evidence: "authority declaration, source proof, owner confirmation, approval log",
    hardRule: "BLOCK purchase when ownership or selling authority conflicts",
    fallback: "Request direct owner confirmation or replace the lot",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D03: {
    domainId: "D03",
    domain: "Supplier reliability and fulfilment",
    phase: "Sourcing",
    owner: "Procurement lead",
    module: "Supplier Scorecard",
    severity: 4,
    likelihoodBand: 4,
    prevention: "Use reliability scores, capacity checks, confirmation deadlines, and limited initial exposure",
    detection: "Alert on late confirmations, repeated shortfalls, substitutions, and response deterioration",
    mitigation: "Split commitments across approved suppliers and release backup supply",
    evidence: "confirmation log, supplied-versus-committed history, exception reasons",
    hardRule: "HOLD buyer confirmation if source confidence is below threshold",
    fallback: "Offer a smaller confirmed quantity or alternate approved lot",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D04: {
    domainId: "D04",
    domain: "Supplier concentration and dependency",
    phase: "Sourcing",
    owner: "General manager",
    module: "Exposure Limits",
    severity: 4,
    likelihoodBand: 3,
    prevention: "Set crop, region, and supplier concentration limits with qualified alternatives",
    detection: "Monitor exposure share, correlated source risks, and declining backup readiness",
    mitigation: "Cap new commitments and activate diversification tasks",
    evidence: "supplier exposure report, backup readiness, concentration approvals",
    hardRule: "BLOCK exposure above the approved concentration ceiling without executive approval",
    fallback: "Reduce demand commitments until independent sources are available",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D05: {
    domainId: "D05",
    domain: "Farm, plot, and crop source records",
    phase: "Sourcing",
    owner: "Quality lead",
    module: "Source Registry",
    severity: 5,
    likelihoodBand: 3,
    prevention: "Capture farm or station, governorate, plot or source reference, crop, variety, harvest date, and handling history",
    detection: "Flag impossible dates, reused source proofs, geospatial conflicts, and unexplained source changes",
    mitigation: "Quarantine the lot until source data is reconciled",
    evidence: "source declaration, crop record, harvest record, photos, reviewer",
    hardRule: "BLOCK lot release when mandatory source fields are incomplete",
    fallback: "Downgrade only if food-use suitability remains verified; otherwise reject",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D06: {
    domainId: "D06",
    domain: "Crop legality and food-use suitability",
    phase: "Sourcing",
    owner: "Quality lead",
    module: "Eligibility Rules",
    severity: 5,
    likelihoodBand: 2,
    prevention: "Maintain crop eligibility rules, prohibited statuses, declarations, and inspection requirements",
    detection: "Check source, prior rejection, suspicious pricing, condemnation evidence, and restricted-use markers",
    mitigation: "Quarantine and escalate to compliance; preserve evidence",
    evidence: "eligibility declaration, inspection, source chain, rejection history",
    hardRule: "BLOCK any lot with uncertain food-use eligibility",
    fallback: "Reject or route only through a separately authorized non-food channel outside the marketplace",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D07: {
    domainId: "D07",
    domain: "Harvest maturity and timing",
    phase: "Supply planning",
    owner: "Quality lead",
    module: "Harvest Window",
    severity: 4,
    likelihoodBand: 4,
    prevention: "Define crop and buyer-specific maturity windows and require planned harvest date and maturity evidence",
    detection: "Compare declared date, appearance, firmness or agreed test, and remaining usable-life estimate",
    mitigation: "Hold, regrade, redirect to a compatible buyer, or reduce committed quantity",
    evidence: "harvest date, maturity measure, sample photos, remaining-life estimate",
    hardRule: "BLOCK sale against a specification whose usable-life minimum is not met",
    fallback: "Match to a faster-use buyer only with explicit acceptance",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D08: {
    domainId: "D08",
    domain: "Supply forecasting and quantity confidence",
    phase: "Supply planning",
    owner: "Procurement lead",
    module: "Supply Forecast",
    severity: 4,
    likelihoodBand: 4,
    prevention: "Store low, expected, and high quantity forecasts with confidence and expiry",
    detection: "Compare forecast changes, historic yield, inspection results, and concurrent reservations",
    mitigation: "Reduce sellable quantity to the confidence-adjusted amount",
    evidence: "forecast version, confidence, inspection, reservation ledger",
    hardRule: "BLOCK commitments above verified available-to-promise quantity",
    fallback: "Wait for recount or source another independently verified lot",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D09: {
    domainId: "D09",
    domain: "Lot existence, reservation, and double-selling",
    phase: "Supply planning",
    owner: "Procurement lead",
    module: "Lot Ledger",
    severity: 5,
    likelihoodBand: 4,
    prevention: "Create immutable lot IDs, supplier confirmation, reservation expiry, and evidence of existence",
    detection: "Detect duplicate photos, overlapping quantities, altered lot IDs, and reservation conflicts",
    mitigation: "Suspend the lot and all dependent commitments",
    evidence: "lot ID, quantity, timestamped evidence, reservation acknowledgement",
    hardRule: "BLOCK any order using an unconfirmed or over-reserved lot",
    fallback: "Rebuild the order from verified alternate lots",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D10: {
    domainId: "D10",
    domain: "Supplier price and term changes",
    phase: "Sourcing",
    owner: "Procurement lead",
    module: "Quote Control",
    severity: 4,
    likelihoodBand: 5,
    prevention: "Version supplier quotes with units, grade, validity, inclusions, and settlement terms",
    detection: "Alert on changes after buyer pricing or outside tolerance",
    mitigation: "Require re-approval and reprice or cancel before purchase",
    evidence: "quote version, acceptance, change reason, approver",
    hardRule: "BLOCK purchase when the active quote no longer supports minimum margin",
    fallback: "Renegotiate quantity or use an alternate source",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D11: {
    domainId: "D11",
    domain: "Climate, weather, and water shock",
    phase: "Supply planning",
    owner: "Procurement lead",
    module: "Agri Alerts",
    severity: 5,
    likelihoodBand: 4,
    prevention: "Map crops and sources to alert zones, seasonal risk windows, and contingency thresholds",
    detection: "Ingest official or vetted alerts and compare field confirmation with forecast deviations",
    mitigation: "Reforecast supply, tighten quality checks, cap commitments, and diversify sources",
    evidence: "alert source, affected crop and region, supplier confirmation, decision log",
    hardRule: "HOLD expansion of commitments during a severe unverified crop-region alert",
    fallback: "Use alternate crops, regions, or smaller confirmed volumes",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D12: {
    domainId: "D12",
    domain: "Pest, disease, and field contamination shock",
    phase: "Supply planning",
    owner: "Food safety lead",
    module: "Agri Alerts",
    severity: 5,
    likelihoodBand: 3,
    prevention: "Require supplier incident declarations and crop-region watchlists",
    detection: "Flag unusual defect patterns, official alerts, correlated supplier reports, and test failures",
    mitigation: "Quarantine affected lots and trigger a source-level investigation",
    evidence: "incident declaration, alert, inspection, test result, disposition",
    hardRule: "BLOCK release where a safety-relevant field incident is unresolved",
    fallback: "Replace supply from an unaffected verified source",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D13: {
    domainId: "D13",
    domain: "Buyer identity and KYB",
    phase: "Buyer onboarding",
    owner: "Sales lead",
    module: "Buyer Registry",
    severity: 5,
    likelihoodBand: 3,
    prevention: "Verify legal or trading identity, location, authorized contacts, and payment identity",
    detection: "Detect duplicate devices, phones, tax IDs, addresses, and inconsistent beneficiary or payer names",
    mitigation: "Disable credit and require verified prepayment while reviewed",
    evidence: "identity proof, verified contact, address, tax data where applicable",
    hardRule: "BLOCK credit and high-value orders for unverified buyers",
    fallback: "Use prepaid small trial only if policy permits",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D14: {
    domainId: "D14",
    domain: "Demand authenticity and purchase intent",
    phase: "Demand",
    owner: "Sales lead",
    module: "Demand Confirmation",
    severity: 5,
    likelihoodBand: 5,
    prevention: "Require quantity, specification, price, acceptance window, payment terms, and explicit confirmation",
    detection: "Score intent from response, deposit, history, duplication, and unusual urgency",
    mitigation: "Reduce or stop procurement exposure until confirmation strengthens",
    evidence: "confirmed order, deposit status, buyer acknowledgement, version history",
    hardRule: "BLOCK demand-led procurement when purchase intent is below threshold",
    fallback: "Offer a quote or sample without reserving capital",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D15: {
    domainId: "D15",
    domain: "Buyer specification clarity",
    phase: "Demand",
    owner: "Sales lead",
    module: "Specification Library",
    severity: 5,
    likelihoodBand: 5,
    prevention: "Use crop and buyer-specific structured specifications with reference images and tolerances",
    detection: "Detect blank, contradictory, copied, or changed fields and mismatch with historic acceptance",
    mitigation: "Freeze the current version and obtain explicit re-acceptance",
    evidence: "specification version, reference images, tolerance, buyer acknowledgement",
    hardRule: "BLOCK fulfilment against an incomplete or unaccepted specification",
    fallback: "Use a standard house grade only after buyer acceptance",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D16: {
    domainId: "D16",
    domain: "Demand forecasting and seasonality",
    phase: "Demand",
    owner: "Sales lead",
    module: "Demand Forecast",
    severity: 4,
    likelihoodBand: 4,
    prevention: "Forecast by buyer, crop, week, scenario, and confidence; separate pipeline from confirmed demand",
    detection: "Compare forecast error, cancellation, holiday, price, and buyer trend signals",
    mitigation: "Reduce speculative exposure and shift to demand-confirmed purchasing",
    evidence: "forecast version, confidence, actuals, error history",
    hardRule: "BLOCK speculative purchasing above the approved risk budget",
    fallback: "Use smaller trial batches and shorter commitment windows",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D17: {
    domainId: "D17",
    domain: "Order confirmation and change control",
    phase: "Demand",
    owner: "Sales lead",
    module: "Order Workflow",
    severity: 5,
    likelihoodBand: 5,
    prevention: "Version every order and require explicit acknowledgement of material changes",
    detection: "Detect edits after confirmation, mismatched copies, and unacknowledged revisions",
    mitigation: "Pause dependent actions and restore the last mutually accepted version",
    evidence: "order versions, acknowledgements, actor, time, reason",
    hardRule: "BLOCK irreversible commitments while a material change is unaccepted",
    fallback: "Renegotiate or cancel using the documented terms",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D18: {
    domainId: "D18",
    domain: "Buyer cancellation, no-show, and retention",
    phase: "Demand",
    owner: "Sales lead",
    module: "Buyer Reliability",
    severity: 5,
    likelihoodBand: 5,
    prevention: "Use cancellation terms, deposits, reliability scores, and exposure caps",
    detection: "Alert on delayed responses, unpaid deposits, repeated changes, and churn signals",
    mitigation: "Stop new exposure, remarket compatible lots, and revise buyer limits",
    evidence: "cancellation history, deposit, response times, profitability",
    hardRule: "BLOCK additional unsecured exposure after reliability thresholds fail",
    fallback: "Use prepaid orders or replace the buyer",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D19: {
    domainId: "D19",
    domain: "Buyer concentration and channel dependency",
    phase: "Demand",
    owner: "General manager",
    module: "Exposure Limits",
    severity: 4,
    likelihoodBand: 4,
    prevention: "Set buyer, segment, and crop revenue exposure limits",
    detection: "Monitor concentration, overdue balances, margin compression, and correlated cancellations",
    mitigation: "Cap exposure and create replacement-demand tasks",
    evidence: "buyer exposure, margin, ageing, replacement pipeline",
    hardRule: "BLOCK unsecured concentration above the approved ceiling",
    fallback: "Diversify across compatible buyer types",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D20: {
    domainId: "D20",
    domain: "Buyer pricing and quote validity",
    phase: "Commercial",
    owner: "Sales lead",
    module: "Quote Control",
    severity: 4,
    likelihoodBand: 5,
    prevention: "Version quotes with unit, grade, quantity, tax, fees, validity, and approval floor",
    detection: "Detect prices below floor, expired quotes, unit mismatches, and manual edits",
    mitigation: "Require re-quote or authorized exception before confirmation",
    evidence: "quote version, cost basis, margin, validity, approver",
    hardRule: "BLOCK orders below margin floor or outside quote validity",
    fallback: "Adjust quantity, specification, or payment terms",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D21: {
    domainId: "D21",
    domain: "Unit economics and margin integrity",
    phase: "Commercial",
    owner: "Finance lead",
    module: "Margin Engine",
    severity: 5,
    likelihoodBand: 5,
    prevention: "Use a versioned cost model with explicit units and conservative shrink and rejection assumptions",
    detection: "Reconcile estimated versus actual contribution and flag unexplained variance",
    mitigation: "Reprice, resize, or reject negative-contribution orders",
    evidence: "cost inputs, formula version, assumptions, actual variance",
    hardRule: "BLOCK confirmation below contribution and cash buffer thresholds",
    fallback: "Run a smaller pilot only with an approved learning budget",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D22: {
    domainId: "D22",
    domain: "Cost leakage and unauthorized spend",
    phase: "Commercial",
    owner: "Finance lead",
    module: "Spend Control",
    severity: 4,
    likelihoodBand: 4,
    prevention: "Use budgets, purchase requests, receipt evidence, categories, and approval limits",
    detection: "Detect split transactions, repeated round amounts, missing receipts, and budget variance",
    mitigation: "Freeze the spend category and reconcile before further payment",
    evidence: "request, approval, receipt, beneficiary, budget code",
    hardRule: "BLOCK out-of-policy spend or approval splitting",
    fallback: "Use an approved petty-cash exception with same-day evidence",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D23: {
    domainId: "D23",
    domain: "Working capital and liquidity",
    phase: "Finance",
    owner: "Finance lead",
    module: "Cash Planner",
    severity: 5,
    likelihoodBand: 5,
    prevention: "Forecast daily cash by committed inflows, outflows, confidence, and downside scenario",
    detection: "Alert on cash gaps, collection slippage, concentration, and unplanned exposure",
    mitigation: "Cap purchasing, accelerate collection, and require deposits",
    evidence: "cash forecast, commitment ledger, ageing, scenario assumptions",
    hardRule: "BLOCK new unsecured commitments below the minimum cash buffer",
    fallback: "Reduce batch size or wait for cleared funds",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D24: {
    domainId: "D24",
    domain: "Deposits and prepayment integrity",
    phase: "Finance",
    owner: "Finance lead",
    module: "Payment Control",
    severity: 5,
    likelihoodBand: 4,
    prevention: "Match cleared funds to order, payer, amount, and currency before status changes",
    detection: "Detect screenshots without bank match, reversals, duplicates, and payer-name mismatches",
    mitigation: "Return the order to payment-pending and reconcile",
    evidence: "bank reference, payer, order allocation, reversal status",
    hardRule: "BLOCK procurement and credit release until funds are cleared and matched",
    fallback: "Request verified payment or reduce exposure",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D25: {
    domainId: "D25",
    domain: "Buyer credit and collections",
    phase: "Finance",
    owner: "Finance lead",
    module: "Credit Ledger",
    severity: 5,
    likelihoodBand: 5,
    prevention: "Set verified limits, terms, ageing rules, security, and automatic exposure calculation",
    detection: "Alert on overdue amounts, broken promises, disputed invoices, and related-party exposure",
    mitigation: "Stop credit, collect deposits, and escalate a documented recovery path",
    evidence: "invoice, acceptance, ageing, promises, credit approval",
    hardRule: "BLOCK new credit when total exposure exceeds limit or ageing rule",
    fallback: "Use cash-before-release until the account cures",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D26: {
    domainId: "D26",
    domain: "Supplier settlement and reconciliation",
    phase: "Finance",
    owner: "Finance lead",
    module: "Settlement Ledger",
    severity: 5,
    likelihoodBand: 4,
    prevention: "Generate settlement from accepted lot, verified weight, active price, and authorized adjustments",
    detection: "Three-way match lot, acceptance, and payment; detect duplicates and beneficiary changes",
    mitigation: "Hold payment and create a variance case",
    evidence: "lot acceptance, weight, price, adjustments, bank proof",
    hardRule: "BLOCK payment on mismatch, duplicate, or unverified beneficiary",
    fallback: "Use manual senior review with complete evidence",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D27: {
    domainId: "D27",
    domain: "Refunds, claims, and dispute handling",
    phase: "Finance",
    owner: "Operations lead",
    module: "Case Management",
    severity: 4,
    likelihoodBand: 4,
    prevention: "Open linked cases with reason codes, evidence deadlines, authority limits, and single disposition",
    detection: "Detect repeated claim patterns, duplicate evidence, unusual approvers, and unresolved ageing",
    mitigation: "Freeze related refunds, preserve the lot record, and escalate",
    evidence: "case, evidence, linked lot and order, decision, payout",
    hardRule: "BLOCK refunds or credits without an approved case and evidence",
    fallback: "Offer a documented non-cash remedy only within policy",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D28: {
    domainId: "D28",
    domain: "Payment fraud and beneficiary changes",
    phase: "Finance",
    owner: "Finance lead",
    module: "Payment Control",
    severity: 5,
    likelihoodBand: 3,
    prevention: "Verify beneficiaries out-of-band, cool down changes, and use maker-checker approval",
    detection: "Alert on new account, device, payee, amount, timing, or unusual sequence",
    mitigation: "Stop payment, lock the profile, and investigate linked accounts",
    evidence: "beneficiary proof, callback, maker-checker log, device and change history",
    hardRule: "BLOCK same-day payment to a newly changed beneficiary",
    fallback: "Pay only the last verified account after independent confirmation",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D29: {
    domainId: "D29",
    domain: "Quality grading and grade integrity",
    phase: "Quality",
    owner: "Quality lead",
    module: "Quality Inspection",
    severity: 5,
    likelihoodBand: 5,
    prevention: "Define crop and buyer grade rules, defect tolerances, reference images, and inspector training",
    detection: "Compare inspectors, buyer outcomes, supplier patterns, and photo evidence",
    mitigation: "Reinspect, regrade, split the lot, and update supplier score",
    evidence: "inspection checklist, sample, photos, inspector, grade version",
    hardRule: "BLOCK release when grade evidence or required tolerance is missing",
    fallback: "Redirect an accurately regraded lot to a compatible buyer",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D30: {
    domainId: "D30",
    domain: "Sampling and inspection integrity",
    phase: "Quality",
    owner: "Quality lead",
    module: "Quality Inspection",
    severity: 5,
    likelihoodBand: 4,
    prevention: "Generate risk-based sample plans, random positions, minimum counts, and sealed evidence",
    detection: "Detect implausibly perfect results, repeated photos, short inspection time, and inspector bias",
    mitigation: "Expand or repeat sampling by a second inspector",
    evidence: "sample plan, selected units, photos, time, inspector, results",
    hardRule: "BLOCK lot acceptance when the required sample is incomplete",
    fallback: "Quarantine until valid sampling is complete",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D31: {
    domainId: "D31",
    domain: "Food safety contamination",
    phase: "Food safety",
    owner: "Food safety lead",
    module: "Food Safety",
    severity: 5,
    likelihoodBand: 3,
    prevention: "Use hazard-based prerequisites, sanitation controls, supplier declarations, inspection, and test rules",
    detection: "Flag symptoms, odors, foreign matter, correlated complaints, failed tests, and hazard alerts",
    mitigation: "Quarantine, stop release, investigate, notify responsible parties, and initiate recall when required",
    evidence: "hazard assessment, monitoring, test, hold and release, corrective action",
    hardRule: "BLOCK release until all critical food-safety holds are closed by an authorized person",
    fallback: "Reject or destroy through an authorized process; never downgrade a safety failure into sale",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D32: {
    domainId: "D32",
    domain: "Pesticide residues, chemicals, and allergens",
    phase: "Food safety",
    owner: "Food safety lead",
    module: "Food Safety",
    severity: 5,
    likelihoodBand: 3,
    prevention: "Capture treatment declarations, risk-based testing, chemical inventories, and segregation rules",
    detection: "Detect missing records, high-risk source patterns, chemical events, and test failures",
    mitigation: "Quarantine affected lots, block linked source, and investigate scope",
    evidence: "treatment record, chemical log, test result, segregation check",
    hardRule: "BLOCK release when a required declaration or result is missing or failed",
    fallback: "Replace from a verified low-risk source",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D33: {
    domainId: "D33",
    domain: "Traceability and recall readiness",
    phase: "Food safety",
    owner: "Food safety lead",
    module: "Traceability",
    severity: 5,
    likelihoodBand: 3,
    prevention: "Assign immutable lot IDs and link source, transformations, splits, merges, buyers, and dispositions",
    detection: "Run completeness checks and timed mock recalls",
    mitigation: "Freeze linked lots and orders, identify scope, document actions, and close only after reconciliation",
    evidence: "lot genealogy, buyer list, quantities, status history, recall log",
    hardRule: "BLOCK any split, merge, or release that breaks lot genealogy",
    fallback: "Use manual verified reconstruction and treat unknown scope conservatively",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D34: {
    domainId: "D34",
    domain: "Weighing, tare, units, and measurement",
    phase: "Intake",
    owner: "Operations lead",
    module: "Weight Capture",
    severity: 5,
    likelihoodBand: 5,
    prevention: "Register scales, units, tare profiles, calibration, dual capture, and edit reasons",
    detection: "Detect impossible deltas, repeated round weights, negative net, scale drift, and operator patterns",
    mitigation: "Reweigh with a verified scale and lock settlement",
    evidence: "gross, tare, net, unit, scale ID, calibration, operator, timestamp",
    hardRule: "BLOCK acceptance or settlement on invalid unit, net weight, or calibration status",
    fallback: "Use a witnessed backup scale and record the exception",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D35: {
    domainId: "D35",
    domain: "Sorting and packing process control",
    phase: "Operations",
    owner: "Operations lead",
    module: "Batch Workflow",
    severity: 4,
    likelihoodBand: 5,
    prevention: "Use batch instructions, line clearance, status separation, yield capture, and supervisor checks",
    detection: "Compare input-output yield, defects, rework, photos, and unexplained variance",
    mitigation: "Stop the batch, segregate outputs, reinspect, and reconcile yield",
    evidence: "batch record, lot inputs, outputs, rejects, operator, checks",
    hardRule: "BLOCK completion when lot identity, yield, or quality checks do not reconcile",
    fallback: "Restart under a verified work instruction",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D36: {
    domainId: "D36",
    domain: "Packaging, crates, labels, and materials",
    phase: "Operations",
    owner: "Operations lead",
    module: "Packaging Control",
    severity: 4,
    likelihoodBand: 5,
    prevention: "Approve material types, inspect condition and cleanliness, print controlled labels, and track reusable assets",
    detection: "Detect label duplicates, wrong crop or lot, damage, missing crates, and abnormal loss",
    mitigation: "Repack, relabel, sanitize, or quarantine before release",
    evidence: "material lot, inspection, label ID, crate movement, cleaning status",
    hardRule: "BLOCK use of unapproved, dirty, damaged, or mismatched packaging",
    fallback: "Use a pre-approved substitute material with recorded compatibility",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D37: {
    domainId: "D37",
    domain: "Storage capacity and allocation",
    phase: "Storage",
    owner: "Operations lead",
    module: "Capacity Planner",
    severity: 5,
    likelihoodBand: 4,
    prevention: "Reserve capacity by zone, crop compatibility, usable-life, and sanitation status before intake",
    detection: "Alert on overbooking, blocked zones, capacity mismatch, and excessive dwell",
    mitigation: "Stop intake, reduce quantity, or redirect to an approved alternative facility",
    evidence: "capacity calendar, slot, compatibility, status, occupancy",
    hardRule: "BLOCK intake when suitable verified capacity is unavailable",
    fallback: "Use a smaller batch or approved alternate storage site",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D38: {
    domainId: "D38",
    domain: "Storage conditions and usable life",
    phase: "Storage",
    owner: "Quality lead",
    module: "Storage Monitoring",
    severity: 5,
    likelihoodBand: 5,
    prevention: "Set crop-zone thresholds, FEFO rules, checks, and remaining-life model",
    detection: "Alert on excursions, missed checks, incompatible co-storage, and accelerating defects",
    mitigation: "Quarantine affected lots, reassess usable life, regrade, and prioritize safe disposition",
    evidence: "condition log, sensor or check, zone, duration, reassessment",
    hardRule: "BLOCK release when a material excursion lacks documented disposition",
    fallback: "Move to compatible approved conditions or safely reject",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D39: {
    domainId: "D39",
    domain: "Inventory accuracy, lot mixing, and status",
    phase: "Storage",
    owner: "Operations lead",
    module: "Inventory Ledger",
    severity: 5,
    likelihoodBand: 5,
    prevention: "Use immutable movements, status-controlled locations, cycle counts, and split-merge genealogy",
    detection: "Detect negative stock, unexplained shrink, duplicate movements, and physical-system variance",
    mitigation: "Freeze affected inventory and reconcile by lot",
    evidence: "movement, count, lot status, actor, location, reason",
    hardRule: "BLOCK allocation of held, missing, rejected, expired, or negative stock",
    fallback: "Use verified count and management-approved adjustment with audit trail",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D40: {
    domainId: "D40",
    domain: "Waste, spoilage, and diversion",
    phase: "Operations",
    owner: "Operations lead",
    module: "Waste Ledger",
    severity: 5,
    likelihoodBand: 5,
    prevention: "Record reason, quantity, lot, evidence, authorization, and final disposition",
    detection: "Detect abnormal yield, repeated reason codes, after-hours activity, and missing proof",
    mitigation: "Secure the lot, recount, investigate, and update corrective actions",
    evidence: "waste record, photos, witness, quantity, disposition proof",
    hardRule: "BLOCK inventory write-off without lot-linked evidence and approval",
    fallback: "Hold in a controlled reject status until lawful disposition",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D41: {
    domainId: "D41",
    domain: "Labour availability, training, and human error",
    phase: "Operations",
    owner: "Operations lead",
    module: "Workforce Control",
    severity: 4,
    likelihoodBand: 5,
    prevention: "Plan coverage, certify critical tasks, use simple checklists, breaks, and role assignment",
    detection: "Alert on uncovered tasks, expired training, excessive hours, repeated errors, and rushed cycle time",
    mitigation: "Pause the task, reassign certified staff, and conduct supervised rework",
    evidence: "roster, certification, checklist, hours, error record",
    hardRule: "BLOCK critical inspection, release, or payment tasks without qualified coverage",
    fallback: "Reduce throughput to the safe staffed capacity",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D42: {
    domainId: "D42",
    domain: "Equipment, scale, and tool readiness",
    phase: "Operations",
    owner: "Operations lead",
    module: "Asset Control",
    severity: 5,
    likelihoodBand: 4,
    prevention: "Maintain asset registry, pre-use checks, preventive maintenance, spares, and calibration",
    detection: "Alert on missed checks, failure trend, abnormal readings, and overdue maintenance",
    mitigation: "Tag out the asset, stop affected work, and inspect output since last known-good check",
    evidence: "asset ID, check, maintenance, calibration, failure and impact assessment",
    hardRule: "BLOCK use of failed, overdue, or unverified critical equipment",
    fallback: "Use a verified backup asset and document the switchover",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D43: {
    domainId: "D43",
    domain: "Hygiene, sanitation, and facility pests",
    phase: "Food safety",
    owner: "Food safety lead",
    module: "Sanitation Control",
    severity: 5,
    likelihoodBand: 4,
    prevention: "Schedule sanitation, verify water and chemical controls, manage pests, and enforce hygiene prerequisites",
    detection: "Detect missed tasks, pest signs, failed swabs or checks, complaints, and recurring hotspots",
    mitigation: "Stop work in the area, protect product, clean, verify, and assess exposed lots",
    evidence: "schedule, task proof, chemical use, pest record, verification, corrective action",
    hardRule: "BLOCK processing or release from an area with an open critical hygiene failure",
    fallback: "Move only unopened verified lots to an approved clean area",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D44: {
    domainId: "D44",
    domain: "Contracts, legal status, and compliance obligations",
    phase: "Governance",
    owner: "Compliance lead",
    module: "Compliance Register",
    severity: 5,
    likelihoodBand: 3,
    prevention: "Maintain entity, facility, food-business, contract, permit, and obligation records with owners and dates",
    detection: "Alert before expiry, detect missing clauses, unapproved templates, and activity-obligation mismatch",
    mitigation: "Stop the affected activity and obtain qualified legal or regulatory review",
    evidence: "registration, permit, contract version, obligation, owner, review",
    hardRule: "BLOCK regulated or high-risk activity without verified current authorization",
    fallback: "Operate only within confirmed scope until advice is obtained",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D45: {
    domainId: "D45",
    domain: "Tax, invoicing, receipts, and record retention",
    phase: "Governance",
    owner: "Finance lead",
    module: "Tax Records",
    severity: 5,
    likelihoodBand: 4,
    prevention: "Create invoice-ready structured records, tax identity checks, document numbering, retention, and integration controls",
    detection: "Reconcile orders, settlements, invoices, returns, and authority submission status where applicable",
    mitigation: "Hold posting, correct through approved document flows, and escalate to tax professionals",
    evidence: "order, invoice or receipt, tax IDs, submission status, credit or return link",
    hardRule: "BLOCK silent deletion or off-ledger alteration of financial records",
    fallback: "Use controlled offline capture and later reconciliation",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D46: {
    domainId: "D46",
    domain: "Insurance and business continuity",
    phase: "Governance",
    owner: "General manager",
    module: "Continuity Planner",
    severity: 5,
    likelihoodBand: 2,
    prevention: "Map critical processes, recovery objectives, coverage, backups, emergency contacts, and exercises",
    detection: "Alert on expired coverage, single points of failure, missed drills, and recovery gaps",
    mitigation: "Activate the incident plan, preserve records and product status, and communicate controlled decisions",
    evidence: "risk register, policy, plan, contacts, drill and corrective action",
    hardRule: "BLOCK critical operation when mandatory contingency or coverage is absent",
    fallback: "Run at a pre-defined reduced safe operating mode",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D47: {
    domainId: "D47",
    domain: "Fraud, collusion, theft, and conflicts of interest",
    phase: "Governance",
    owner: "General manager",
    module: "Integrity Monitoring",
    severity: 5,
    likelihoodBand: 3,
    prevention: "Segregate duties, declare conflicts, rotate sensitive tasks, and set approval limits",
    detection: "Use anomaly detection across relationships, devices, decisions, timing, prices, weights, and overrides",
    mitigation: "Freeze linked transactions, preserve logs, and run an independent investigation",
    evidence: "actor graph, decision log, conflicts, overrides, evidence, case",
    hardRule: "BLOCK self-approval and conflicted maker-checker combinations",
    fallback: "Route to an independent authorized reviewer",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D48: {
    domainId: "D48",
    domain: "Marketplace bypass, side deals, and reputation",
    phase: "Governance",
    owner: "General manager",
    module: "Relationship Governance",
    severity: 4,
    likelihoodBand: 4,
    prevention: "Use clear participation terms, relationship ownership, protected communications, fair dispute handling, and value-added retention",
    detection: "Detect unusual contact changes, disappearing activity, duplicate parties, complaints, and pricing leakage",
    mitigation: "Review the relationship, adjust privileges, and preserve fair access to records and disputes",
    evidence: "terms acceptance, communications metadata, cases, linked identities",
    hardRule: "BLOCK punitive automated decisions without documented review and appeal",
    fallback: "Use transparent graduated restrictions and verified re-onboarding",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D49: {
    domainId: "D49",
    domain: "Communication and acknowledgement",
    phase: "Cross-functional",
    owner: "Operations lead",
    module: "Communications Hub",
    severity: 4,
    likelihoodBand: 5,
    prevention: "Convert critical messages into structured records with owner, deadline, language, version, and acknowledgement",
    detection: "Alert on unread changes, contradictory messages, ambiguous units, and missed response deadlines",
    mitigation: "Pause affected commitments and obtain a clear acknowledged instruction",
    evidence: "message, structured summary, version, sender, recipient, acknowledgement",
    hardRule: "BLOCK material changes based only on an unacknowledged informal message",
    fallback: "Use a verified phone confirmation logged by two parties",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D50: {
    domainId: "D50",
    domain: "Roles, permissions, and approval governance",
    phase: "Platform",
    owner: "Security lead",
    module: "Access Control",
    severity: 5,
    likelihoodBand: 3,
    prevention: "Use least privilege, maker-checker, role review, strong authentication, and protected audit logs",
    detection: "Alert on privilege changes, self-approval, dormant accounts, unusual access, and override bursts",
    mitigation: "Revoke access, freeze affected records, and review the action history",
    evidence: "role, approval matrix, login, change and audit logs",
    hardRule: "BLOCK self-approval, shared accounts, and destructive changes without protected workflow",
    fallback: "Use time-limited emergency access with retrospective review",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D51: {
    domainId: "D51",
    domain: "Data quality and master-data integrity",
    phase: "Platform",
    owner: "Data owner",
    module: "Data Governance",
    severity: 5,
    likelihoodBand: 5,
    prevention: "Own canonical master data, validation, deduplication, effective dates, and change approval",
    detection: "Detect outliers, orphan records, conflicting units, duplicate entities, and downstream variance",
    mitigation: "Quarantine affected calculations and rebuild from the last verified version",
    evidence: "master record, version, owner, validation, lineage",
    hardRule: "BLOCK ambiguous units and retroactive silent edits",
    fallback: "Use a controlled correction with impact report",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D52: {
    domainId: "D52",
    domain: "Cybersecurity, privacy, and account abuse",
    phase: "Platform",
    owner: "Security lead",
    module: "Security Center",
    severity: 5,
    likelihoodBand: 3,
    prevention: "Use MFA where practical, secure recovery, encryption, rate limits, secrets management, and data minimization",
    detection: "Alert on impossible access, credential stuffing, export spikes, device change, and suspicious automation",
    mitigation: "Lock accounts, revoke sessions, preserve evidence, notify responsible owners, and recover safely",
    evidence: "login and device logs, permissions, export log, security case",
    hardRule: "BLOCK high-risk actions after suspicious authentication or recovery",
    fallback: "Use verified manual recovery with least data exposure",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D53: {
    domainId: "D53",
    domain: "System reliability, offline work, and integrations",
    phase: "Platform",
    owner: "Technology lead",
    module: "Reliability Console",
    severity: 5,
    likelihoodBand: 4,
    prevention: "Use idempotency, queues, version checks, offline identifiers, backups, monitoring, and reconciliation",
    detection: "Detect stuck states, duplicates, sync conflicts, latency, schema drift, and backup failure",
    mitigation: "Enter controlled degraded mode, stop unsafe actions, reconcile, and replay idempotently",
    evidence: "request ID, state transition, sync version, integration log, recovery record",
    hardRule: "BLOCK repeated irreversible actions without an idempotency key and confirmed state",
    fallback: "Capture signed offline evidence and reconcile before dependent actions",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
  D54: {
    domainId: "D54",
    domain: "Automated decisions, scoring, and calculation correctness",
    phase: "Platform",
    owner: "Product owner",
    module: "Decision Governance",
    severity: 5,
    likelihoodBand: 4,
    prevention: "Version formulas and models, define units, test boundaries, expose reason codes, and require human authority for critical outcomes",
    detection: "Run shadow checks, invariant tests, drift analysis, appeal patterns, and protected canaries",
    mitigation: "Disable the rule, revert to the last verified version, and reassess affected records",
    evidence: "input snapshot, version, output, explanation, test and override log",
    hardRule: "BLOCK autonomous food-safety release, legal judgment, or irreversible payment decision",
    fallback: "Use a conservative manual workflow with documented review",
    acceptanceTests: ["The normal valid path succeeds and records the evidence, actor, and rule version.","A missing mandatory input is rejected with a clear correction path.","A stale or conflicting version cannot silently overwrite a confirmed record.","An unauthorized actor cannot approve or bypass the rule.","Offline or repeated submission does not duplicate the action.","An exception is time-limited, reasoned, approved, and auditable."],
  },
});

export type DomainId = keyof typeof CONTROLS;

export const MODULES = ["Access Control","Agri Alerts","Asset Control","Batch Workflow","Buyer Registry","Buyer Reliability","Capacity Planner","Case Management","Cash Planner","Communications Hub","Compliance Register","Continuity Planner","Credit Ledger","Data Governance","Decision Governance","Demand Confirmation","Demand Forecast","Eligibility Rules","Exposure Limits","Food Safety","Harvest Window","Integrity Monitoring","Inventory Ledger","Lot Ledger","Margin Engine","Order Workflow","Packaging Control","Payment Control","Quality Inspection","Quote Control","Relationship Governance","Reliability Console","Sanitation Control","Security Center","Settlement Ledger","Source Registry","Specification Library","Spend Control","Storage Monitoring","Supplier Registry","Supplier Scorecard","Supply Forecast","Tax Records","Traceability","Waste Ledger","Weight Capture","Workforce Control"] as const;

export const controlsForModule = (m: string): ControlRequirement[] =>
  Object.values(CONTROLS).filter((c) => c.module === m);

export const blockingControls = (): ControlRequirement[] =>
  Object.values(CONTROLS).filter((c) => c.hardRule.startsWith('BLOCK'));
